import type { Metadata } from "next";
import { ReactQueryClientProvider } from "@/components/providers";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    zyg: {
      authToken: string;
      widgetId: string;
    };
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <script async src="loader.js"></script>
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryClientProvider>
  );
}
